"""De installer (V23, v0.15): het wheel krijgt de versies uit uv.lock (installer/pin_dependencies.py)."""

import importlib.util
import tomllib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("pin_dependencies", ROOT / "installer" / "pin_dependencies.py")
pin_dependencies = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pin_dependencies)

EXPORT = """# This file was autogenerated by uv via the following command:
#    uv export --frozen --no-hashes --no-emit-project --extra server
cadquery==2.8.0
    # via camtocad
fastapi==0.143.0
    # via camtocad
numpy==2.4.6 ; python_full_version < '3.12'
    # via camtocad
numpy==2.5.3 ; python_full_version >= '3.12'
opencv-python-headless==5.0.0.93
pi-heif==1.4.0
uvicorn==0.54.0
"""


def test_the_wheel_of_the_installer_gets_the_locked_versions(tmp_path):
    reqs = pin_dependencies.pinned(EXPORT)
    assert reqs[0] == "cadquery==2.8.0" and "numpy==2.4.6 ; python_full_version < '3.12'" in reqs and len(reqs) == 7
    toml = tmp_path / "pyproject.toml"
    toml.write_text((ROOT / "pyproject.toml").read_text(encoding="utf-8"), encoding="utf-8")
    assert pin_dependencies.main([str(_write(tmp_path / "vast.txt", EXPORT)), str(toml)]) == 0
    before = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    after = tomllib.loads(toml.read_text(encoding="utf-8"))
    assert after["project"]["dependencies"] == reqs
    del before["project"]["dependencies"], after["project"]["dependencies"]
    assert after == before  # de rest (naam, versie, extra's, scripts) blijft gelijk


def test_an_incomplete_export_is_refused():
    with pytest.raises(ValueError, match="fastapi"):  # zonder --extra server
        pin_dependencies.pinned("cadquery==2.8.0\nnumpy==2.4.6\nopencv-python-headless==5.0.0.93\n")
    with pytest.raises(ValueError, match="no-hashes"):
        pin_dependencies.pinned(EXPORT.replace("cadquery==2.8.0", "cadquery==2.8.0 \\"))


def _write(path: Path, text: str) -> Path:
    path.write_text(text, encoding="utf-8")
    return path
